---
- name: Create runtime dir for Zabbix Server
  file: path=/run/zabbix-server state=directory
        owner={{ zbx_os_user_server }} group={{ zbx_os_group_server }}

- name: Create runtime dir for Zabbix Agentd
  file: path=/run/zabbix-agentd state=directory
        owner={{ zbx_os_user_agentd }} group={{ zbx_os_group_agentd }}

- name: Copy Zabbix unit files
  templates: src=templates/{{ item.src }}
             dest=/etc/systemd/system/{{ item.dest }}
             mode=0664
  with_items:
    - { src: 'zabbix-server.service.j2', dest: 'zabbix-server.service' }
    - { src: 'zabbix-agentd.service.j2', dest: 'zabbix-agentd.service' }
