---
- name: Create runtime dir for Zabbix Server
  file: path=/run/zabbix-server state=directory
        owner={{ zbx_os_user_server }} group={{ zbx_os_group_server }}

- name: Create runtime dir for Zabbix Agentd
  file: path=/run/zabbix-agentd state=directory
        owner={{ zbx_os_user_agentd }} group={{ zbx_os_group_agentd }}

- name: Copy Zabbix unit files
  templates: src={{ item.src }} dest={{ item.dest }} mode=0664
  with_items:
    - { src: 'templates/zabbix-server.service.j2', dest: '/etc/systemd/system/zabbix-server.service' }
    - { src: 'templates/zabbix-agentd.service.j2', dest: '/etc/systemd/system/zabbix-agentd.service' }
